<?php
/**
 * Created by PhpStorm.
 * User: zhangziang
 * Date: 2018/10/17
 * Time: 上午12:38
 */

namespace App\Dao;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
class DaoTodoBase extends Model{
    public $objDao;
    public function __construct(array $attributes = []){
        parent::__construct($attributes);
        $this->objDao=DB::table('todo');
    }

//`id` bigint(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
//`timestart` int(11) NOT NULL DEFAULT '0' COMMENT '开始时间',
//`timeend` int(11) NOT NULL COMMENT '结束时间',
//`title` varchar(64) NOT NULL COMMENT '标题',
//`note` varchar(256) NOT NULL COMMENT '详细信息',
//`ctime` int(11) NOT NULL COMMENT '创建时间',
//`mtime` int(11) NOT NULL COMMENT '改变时间',
//`use_time` int(11) NOT NULL DEFAULT '0' COMMENT '需要时间',
//`user_id` int(11) NOT NULL COMMENT '用户id',
//`level` tinyint(4) NOT NULL COMMENT '优先级',
//`status` tinyint(4) NOT NULL COMMENT '状态',
//`pid` int(11) NOT NULL DEFAULT '0' COMMENT '父任务',
//`is_changed` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否改变过',
//`stage` tinyint(4) NOT NULL COMMENT '阶段',

    public function addOne($userid,$timestart,$timeend,$title,$note,$use_time,$tag,$status,$stage,$level=0,$pid=0,$is_change=0){
        $ctime=time();
        $mtime=$ctime;
        return $this->objDao->insertGetId(
            [
                'timestart'=>$timestart,
                'timeend'=>$timeend,
                'title'=>$title,
                'note'=>$note,
                'ctime'=>$ctime,
                'mtime'=>$mtime,
                'use_time'=>$use_time,
                'user_id'=>$userid,
                'level'=>$level,
                'status'=>$status,
                'pid'=>$pid,
                'is_changed'=>$is_change,
                'stage'=>$stage,
                'tag'=>$tag,
            ]
        );
    }
    public function update(array $attributes = [], array $options = [])
    {
        return parent::update($attributes, $options); // TODO: Change the autogenerated stub
    }
    public function getTodoByid($id){
       return  $this->objDao->where('id',intval($id))->first();
    }
    public function edit($param){
//        var_dump($param);
        $id=$param['id'];
        unset($param['id']);
        $conf=array(
            "startTime"=>'timestart',
            "endTime"=>'timeend',
            "useTime"=>'use_time',
        );
        $confkeys=array_keys($conf);
        foreach ($param as $key=>$val){
            if(in_array($key,$confkeys)){
                $param[$conf[$key]]=$val;
                unset($param[$key]);
            }
        }
        return $this->objDao->where('id',$id)->update($param);
    }
    public function getList($userid){
        return $this->objDao->where('user_id','=',$userid)->get();
    }
    function changeParam(){
        $list=["startTime","endTime","title","note","level","tag","useTime",'id'];


    }
}